# This file configures the analyzer, which statically analyzes Dart code to
# check for errors, warnings, and lints.
#
# The issues identified by the analyzer are surfaced in the UI of Dart-enabled
# IDEs (https://dart.dev/tools#ides-and-editors). The analyzer can also be
# invoked from the command line by running `flutter analyze`.

# The following line activates a set of recommended lints for Flutter apps,
# packages, and plugins designed to encourage good coding practices.
include:
  - package:flutter_lints/flutter.yaml
  - package:bloc_lint/recommended.yaml

linter:
  # The lint rules applied to this project can be customized in the
  # section below to disable rules from the `package:flutter_lints/flutter.yaml`
  # included above or to enable additional rules. A list of all available lints
  # and their documentation is published at https://dart.dev/lints.
  #
  # Instead of disabling a lint rule for the entire project in the
  # section below, it can also be suppressed for a single line of code
  # or a specific dart file by using the `// ignore: name_of_lint` and
  # `// ignore_for_file: name_of_lint` syntax on the line or in the file
  # producing the lint.
  rules:
    # 文档规则
    comment_references: true
    dangling_library_doc_comments: true
    document_ignores: true
    missing_code_block_language_in_doc_comment: true
    public_member_api_docs: true
    slash_for_doc_comments: true
    unintended_html_in_doc_comment: true
    # 测试规则
    test_types_in_equals: true
    use_test_throws_matchers: true

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
