name: qtconsult_studio
description: 量潮咨询服务看板

publish_to: 'none'
version: 0.3.0

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
  bloc: ^9.2.1
  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  flutter_quanttide_project: ^0.1.0
  http: ^1.2.0
  quanttide_project: ^0.2.0
  web: ^1.1.0

dev_dependencies:
  bloc_lint: ^0.4.3
  environment_config: ^4.1.2
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/fixtures/workspace0/project0.json
    - assets/fixtures/workspace1/project1.json
