name: qtconsult_project
description: 量潮咨询 OODA 看板模型
version: 0.1.0

environment:
  sdk: ^3.11.5

dependencies:
  data_sources:
    path: ../data-sources
  quanttide_project: ^0.2.0
  flutter_quanttide_project: ^0.1.0
  flutter:
    sdk: flutter
  provider: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
